language: cpp

os: 
- linux

before_install:
  - sudo apt-get update

script:
- mkdir build
- cd build
- cmake .. -DGMX_BUILD_OWN_FFTW=ON
- make -j
- sudo make install
- source /usr/local/gromacs/bin/GMXRC

